name: book_reader
description: A widget used to read a book.
version: 0.0.17
homepage: https://github.com/CalsRanna/book_reader
repository: https://github.com/CalsRanna/book_reader

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
